### ISSUE TITLE
Checkout not possible in 5.1.3

### ISSUE THREAD

**Issue by msslovi0** [shopwareLabs/SwagProfiling#2]
With SwagProfiling active it is not possible to checkout using Shopware 5.1.3. 

When you click on 'Zahlungspflichtig bestellen' the confirmation page is loaded again and at the bottom the following error is displayed:
`<b>Fatal error</b>:  Uncaught exception 'PDOException' with message 'You cannot serialize or unserialize PDO instances' in /var/www/kd/dev/engine/Library/Zend/Session.php:771
Stack trace:`
`#0 [internal function]: PDO-&gt;__sleep()`
`#1 [internal function]: ArrayObject-&gt;serialize()`
`#2 [internal function]: ArrayObject-&gt;serialize()`
`#3 /var/www/kd/dev/engine/Library/Zend/Session.php(771): session_write_close()`
`#4 /var/www/kd/dev/engine/Library/Zend/Session/SaveHandler/DbTable.php(217): Zend_Session::writeClose()`
`#5 [internal function]: Zend_Session_SaveHandler_DbTable-&gt;__destruct()`
`#6 {main}
  thrown in <b>/var/www/kd/dev/engine/Library/Zend/Session.php</b> on line <b>771</b><br />`

**Comment by mitelg** [comment]
Hi, 
we recommend to use https://github.com/shyim/shopware-profiler instead of this old plugin
I will close this issue for now
