### ISSUE TITLE
Error with 5.2.x

### ISSUE THREAD

**Issue by 8mylez** [shopwareLabs/SwagProfiling#3]
The method https://github.com/shopwareLabs/SwagProfiling/blob/master/Bootstrap.php#L277 was removed in 5.2

I think the easiest way to solve this issue is to remove the configuration tab.

Which method should be used instead of getOptions (https://github.com/shopwareLabs/SwagProfiling/blob/master/Bootstrap.php#L277) ?

Any ideas? @bcremer

**Comment by bcremer** [comment]
A replacement would be `Shopware()->Container()->getParameterBag()->all()`, see 
https://github.com/shyim/shopware-profiler/blob/master/Components/Collectors/ConfigCollector.php#L16.

In general I can recommend [`ShyimProfiler`](https://github.com/shyim/shopware-profiler) as a more up-to-date replacement for SwagProfiler.
